@echo off
echo Starting EDAV Backend Server...
cd backend
echo Checking if port 3001 is available...
netstat -an | findstr :3001 > nul
if %errorlevel% == 0 (
    echo Port 3001 is in use, killing process...
    for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3001') do taskkill /PID %%a /F > nul 2>&1
    timeout /t 2 > nul
)
echo Starting server on port 3001...
npm start