console.log('🍍 Pinata IPFS Setup (FREE)');
console.log('');
console.log('📋 Steps to get FREE Pinata API keys:');
console.log('');
console.log('1. Visit: https://pinata.cloud/');
console.log('2. Click "Sign Up" (no credit card needed)');
console.log('3. Verify your email');
console.log('4. Go to API Keys section');
console.log('5. Create new API key with these permissions:');
console.log('   - pinFileToIPFS');
console.log('   - pinJSONToIPFS');
console.log('6. Copy API Key and Secret');
console.log('');
console.log('🔧 Update your .env file:');
console.log('PINATA_API_KEY=your_actual_api_key');
console.log('PINATA_SECRET_KEY=your_actual_secret_key');
console.log('');
console.log('💰 Free Tier Limits:');
console.log('- 1GB storage');
console.log('- 100GB bandwidth/month');
console.log('- Perfect for development!');
console.log('');
console.log('🚀 After setup, your IPFS will work with real storage!');